[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dugout = "aj3cxAukKLLjx92twBbkiZXqx98xE7ixc1vnNTZcHPE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000